dependencies {
    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.6.0'
    implementation 'com.auth0:java-jwt:4.4.0'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'com.fatboyindustrial.gson-javatime-serialisers:gson-javatime-serialisers:1.1.2'

    testImplementation 'org.springframework.security:spring-security-test'

    implementation project(':model')
    implementation project(':usecase')
}