server:
  port: 8081
springdoc:
  swagger-ui:
    path: "/doc/swagger-ui/index.html"
  api-docs:
    path: "/doc/api-docs"
spring:
  webflux:
    base-path: "/iasapi"
  application:
    name: event-management-challenge
  profiles:
    active: dev
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
logging:
  level:
    com.ias: DEBUG
    org.slf4j: DEBUG
aws:
  region: "us-east-1"
  secrets:
    rabbitmq-secret-name: "rabbitmq-secret-name"